# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Hassan-tech-pro/ml-internship/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

In [2]:
from google.colab import userdata
userdata.get('fr_internship')

'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'

In [10]:
# This cell is for CODE (numbers, a query, a check).
import duckdb
from google.colab import userdata

try:
    hf_token = userdata.get('fr_internship')
except Exception:
    hf_token = fr_internship

con = duckdb.connect()
con.execute(f"CREATE SECRET hf_auth (TYPE huggingface, TOKEN '{hf_token}');")

rel = "hf://datasets/FlyRank/internship-warehouse"
month_path = f"{rel}/fact_content_daily_performance/month=2026-03/*.parquet"

# Query 1: Verify Time Window using report_date
query_1 = f"""
SELECT
    COUNT(*) AS total_rows,
    MIN(report_date) AS start_date,
    MAX(report_date) AS end_date
FROM read_parquet('{month_path}');
"""

df_window = con.sql(query_1).df()
print("--- Section 1 Verification ---")
display(df_window)
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

--- Section 1 Verification ---

   total_rows start_date   end_date
0     9841378 2026-03-01 2026-03-31

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

In [11]:
# This cell is for CODE (numbers, a query, a check).
query_2 = f"""
SELECT *
FROM read_parquet('{month_path}')
LIMIT 1;
"""

df_sample = con.sql(query_2).df()
print("--- Section 2: Available Columns ---")
for col in df_sample.columns:
    print(f" - {col}")
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

--- Section 2: Available Columns ---
 - report_date
 - client_hash_id
 - content_hash_id
 - client_has_gsc
 - client_has_ga4
 - gsc_data_available
 - ga4_data_available
 - gsc_impressions
 - gsc_clicks
 - gsc_sum_position
 - gsc_avg_position
 - ga4_pageviews
 - ga4_sessions
 - ga4_users
 - ga4_engaged_sessions
 - ga4_total_engagement_sec
 - sessions_organic
 - sessions_direct
 - sessions_referral
 - sessions_social
 - sessions_paid
 - sessions_ai
 - ai_chatgpt
 - ai_perplexity
 - ai_gemini
 - ai_copilot
 - ai_claude
 - ai_meta
 - ai_other
 - scroll_events
 - month

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

In [12]:
# This cell is for CODE (numbers, a query, a check).
# Fact 1: Grain Uniqueness check on (report_date, content_hash_id)
q_grain = f"""
SELECT report_date, content_hash_id, COUNT(*) as row_count
FROM read_parquet('{month_path}')
GROUP BY report_date, content_hash_id
HAVING COUNT(*) > 1
LIMIT 5;
"""
duplicates = con.sql(q_grain).df()
print(f"Fact 1 (Grain Check) - Duplicates found: {len(duplicates)}")

# Fact 2: Row Counts & Metric Coverage
q_counts = f"""
SELECT
    COUNT(*) as total_rows,
    COUNT(gsc_clicks) as non_null_clicks,
    COUNT(gsc_impressions) as non_null_impressions
FROM read_parquet('{month_path}');
"""
print("\n--- Fact 2: Row Counts ---")
display(con.sql(q_counts).df())

# Fact 3: Availability Filter (IS TRUE)
q_availability = f"""
SELECT
    COUNT(*) as survived_rows
FROM read_parquet('{month_path}')
WHERE gsc_data_available IS TRUE;
"""
print("\n--- Fact 3: Availability Check (IS TRUE) ---")
display(con.sql(q_availability).df())
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Fact 1 (Grain Check) - Duplicates found: 0

--- Fact 2: Row Counts ---

   total_rows  non_null_clicks  non_null_impressions
0     9841378          9841378               9841378

--- Fact 3: Availability Check (IS TRUE) ---

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   survived_rows
0        3611061

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

In [13]:
# This cell is for CODE (numbers, a query, a check).
q_limits = f"""
SELECT
    MIN(gsc_clicks) as min_clicks,
    MAX(gsc_clicks) as max_clicks,
    AVG(gsc_clicks) as avg_clicks,
    MIN(gsc_impressions) as min_impressions,
    MAX(gsc_impressions) as max_impressions
FROM read_parquet('{month_path}');
"""
print("--- Section 4: Data Limits Check ---")
display(con.sql(q_limits).df())
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

--- Section 4: Data Limits Check ---

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   min_clicks  max_clicks  avg_clicks  min_impressions  max_impressions
0           0         274    0.083508                0            40084

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.